# Generated by Django 5.2.7 on 2026-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_configuracao_dias_gratuitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='Token_mercadolivre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='client_id_mercadolivre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='secret_mercadolivre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='access_token_mercadopago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='public_key_mercadopago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='webhook_secret_mercadopago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
