# Generated by Django 5.2.7 on 2026-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenantsettings_chamar_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='aberto',
        ),
        migrations.AddField(
            model_name='tenant',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
