# Generated by Django 5.2.7 on 2026-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_remove_tenant_aberto_tenant_facebook_pixel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='codigo_do_fluxo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
