# Generated by Django 5.2.7 on 2026-09-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_tenantsettings_codigo_do_fluxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='aberto',
            field=models.BooleanField(default=False),
        ),
    ]
