# Generated by Django 5.2.7 on 2026-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_user_data_expiracao_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
