# Generated by Django 5.2.7 on 2026-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_user_email_confirmation_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
