ETAPAS = [
    {
        'status': 'novo',
        'titulo': 'Pedido recebido',
        'gatilho': 'Assim que o pedido entrar no sistema',
        'icone': 'fa-inbox',
        'cor': 'warning',
        'mensagem': 'Olá, {cliente}! Recebemos o seu pedido #{pedido} na {loja}. Total: {total}. Em breve confirmaremos o atendimento.',
    },
    {
        'status': 'confirmado',
        'titulo': 'Pedido confirmado',
        'gatilho': 'Ao clicar em Confirmar pedido',
        'icone': 'fa-check-circle',
        'cor': 'primary',
        'mensagem': 'Olá, {cliente}! Seu pedido #{pedido} foi confirmado pela {loja}. Vamos iniciar a separação dos produtos.',
    },
    {
        'status': 'processando',
        'titulo': 'Em preparação',
        'gatilho': 'Ao clicar em Aceitar pedido ou Iniciar preparação',
        'icone': 'fa-fire',
        'cor': 'primary',
        'mensagem': '{cliente}, seu pedido #{pedido} já está em preparação. Avisaremos você quando estiver pronto.',
    },
    {
        'status': 'pronto',
        'titulo': 'Pedido pronto',
        'gatilho': 'Ao clicar em Marcar como pronto',
        'icone': 'fa-box-open',
        'cor': 'info',
        'mensagem': 'Boa notícia, {cliente}! Seu pedido #{pedido} está pronto. Modalidade: {tipo_entrega}.',
    },
    {
        'status': 'enviado',
        'titulo': 'Saiu para entrega',
        'gatilho': 'Ao clicar em Saiu para entrega ou Pedido enviado',
        'icone': 'fa-motorcycle',
        'cor': 'info',
        'mensagem': '{cliente}, o pedido #{pedido} saiu para entrega. Endereço: {endereco}.',
    },
    {
        'status': 'concluido',
        'titulo': 'Pedido concluído',
        'gatilho': 'Ao clicar em Concluir pedido, Entregue ou Retirado',
        'icone': 'fa-star',
        'cor': 'success',
        'mensagem': 'Pedido #{pedido} concluído, {cliente}! A {loja} agradece pela preferência. Esperamos atender você novamente.',
    },
    {
        'status': 'cancelado',
        'titulo': 'Pedido cancelado',
        'gatilho': 'Ao confirmar o cancelamento do pedido',
        'icone': 'fa-times-circle',
        'cor': 'danger',
        'mensagem': 'Olá, {cliente}. O pedido #{pedido} foi cancelado. Se precisar de ajuda, fale com a {loja} pelo {whatsapp_loja}.',
    },
]

VARIAVEIS = [
    ('{cliente}', 'Nome do cliente'),
    ('{telefone}', 'WhatsApp do cliente'),
    ('{pedido}', 'Número do pedido'),
    ('{loja}', 'Nome da loja'),
    ('{status}', 'Etapa atual'),
    ('{total}', 'Valor total'),
    ('{tipo_entrega}', 'Entrega ou retirada'),
    ('{endereco}', 'Endereço de entrega'),
    ('{pagamento}', 'Forma de pagamento'),
    ('{data}', 'Data do pedido'),
    ('{hora}', 'Hora do pedido'),
    ('{whatsapp_loja}', 'WhatsApp da loja'),
]
